In [1]:
pwd

'C:\\Users\\hp\\Desktop\\Other\\Coding_Projects\\Simple_Coding_Examples'

In [2]:
# see the info of the notebook
import session_info
session_info.show()

In [3]:
# import libs.
import pandas as pd
import numpy as np

# Import the data file in fasta fromat

In [4]:
df = pd.read_csv('SARS_CORONAVIRUS_NC_045512_sequence.fasta', header = None)[1:][0]
df = pd.DataFrame(df)
df.columns = ['Genome Sequence']
df.columns, df.shape

(Index(['Genome Sequence'], dtype='object'), (428, 1))

# Filtering 
Remove seqs less than the median length

In [7]:
# Find the length of each sequence in the DataFrame and store the result in a new column named 'Length'.
lengths = []
for i in df['Genome Sequence']:
    lengths.append(len(i))
    
df['Length'] = lengths
# Calculate the median length of the genome sequences and store the result in a variable named 'median_len'.
median_len = df['Length'].median()

# Remove all rows from the DataFrame that do not have the length equal to the median length.
df.drop(df.loc[df['Length'] != median_len].index, inplace=True)

# Matching
Find matches of a sub-sequences


In [8]:
# check if any sequence in df contains the subseq: 'TAATTTAGGCATGCCTT'
def isSubSequence(str1, str2):
    m = len(str1)
    n = len(str2)
 
    j = 0    # Index of str1
    i = 0    # Index of str2
 
    # Traverse both str1 and str2
    # Compare current character of str2 with
    # first unmatched character of str1
    # If matched, then move ahead in str1
 
    while j < m and i < n:
        if str1[j] == str2[i]:
            j = j+1
        i = i + 1
 
    # If all characters of str1 matched,
    # then j is equal to m
    return j == m


# Drive the created function
u = []
str2 = "TAATTTAGGCATGCCTT"

for i in df["Genome Sequence"]:
    if isSubSequence(i, str2):
        u.append(1)
    else:
        u.append(0)

df['Match'] = u
df

Genome Sequence  Length  Match
1    ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...      70      0
2    CGAACTTTAAAATCTGTGTGGCTGTCACTCGGCTGCATGCTTAGTG...      70      0
3    TAATTACTGTCGTTGACAGGACACGAGTAACTCGTCTATCTTCTGC...      70      0
4    TTGCAGCCGATCATCAGCACATCTAGGTTTCGTCCGGGTGTGACCG...      70      0
5    CCTGGTTTCAACGAGAAAACACACGTCCAACTCAGTTTGCCTGTTT...      70      0
..                                                 ...     ...    ...
423  CAGACCACACAAGGCAGATGGGCTATATAAACGTTTTCGCTTTTCC...      70      0
424  GTGCAGAATGAATTCTCGTAACTACATAGCACAAGTAGATGTAGTT...      70      0
425  TTAATCAGTGTGTAACATTAGGGAGGACTTGAAAGAGCCACCACAT...      70      0
426  GATCGAGTGTACAGTGAACAATGCTAGGGAGAGCTGCCTATATGGA...      70      0
427  TTTAGTAGTGCTATCCCCATGTGATTTTAATAGCTTCTTAGGAGAA...      70      0

[427 rows x 3 columns]

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 427 entries, 1 to 427
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Genome Sequence  427 non-null    object
 1   Length           427 non-null    int64 
 2   Match            427 non-null    int64 
dtypes: int64(2), object(1)
memory usage: 10.1+ KB


# Find differences

In [10]:
# create an array with zeros
n = len(df['Length'])
my_array = np.zeros((n,n))
differences = np.zeros((n,n))

# define a function to get the differneces:
def getDifference(x, y): # x, y are the seqs
    return sum(a != b for (a,b) in zip(x, y)) # this function counts the differences

# apply the function to get the differences matrix
for i, p in enumerate(df['Genome Sequence']):
    for j, p2 in enumerate(df['Genome Sequence']):
        if j >= i:
            break
        differences[i, j] = getDifference(p, p2)
        differences[j, i] = differences[i, j]

# print the differences matrix
print(differences)


[[ 0. 51. 50. ... 49. 51. 50.]
 [51.  0. 57. ... 53. 54. 54.]
 [50. 57.  0. ... 60. 48. 58.]
 ...
 [49. 53. 60. ...  0. 59. 48.]
 [51. 54. 48. ... 59.  0. 44.]
 [50. 54. 58. ... 48. 44.  0.]]


In [11]:
np.info(differences)

class:  ndarray
shape:  (427, 427)
strides:  (3416, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x2d49d6a4040
byteorder:  little
byteswap:  False
type: float64


In [12]:
np.min(my_array)

0.0

# The simialr sequences

In [19]:
# find the two most similar genome sequences
similar_indices = np.unravel_index(np.argmin(differences), differences.shape)
similar = (similar_indices[0], similar_indices[1])
print("The two most similar genome sequences are rows", similar)
print()
print("The two most similar genome sequences are:")
print(df.iloc[similar[0]][0])
print(df.iloc[similar[1]][0])

The two most similar genome sequences are rows (0, 0)

The two most similar genome sequences are:
ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGTAGATCTGTTCTCTAAA
ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGTAGATCTGTTCTCTAAA
